name:                plunder
version:             0.1.0.0
license:             AGPL
author:              "Plunder Authors"
maintainer:          "plun@pqrs.me"
copyright:           "2021 Plunder Authors"

cc-options: -Wall -O3

library:
  source-dirs: lib

executables:
  rex:
    main: Main.hs
    source-dirs: exe/rex
    dependencies:
      - plunder

  sire:
    main: Main.hs
    source-dirs: exe/sire
    dependencies:
      - plunder
      - rainbow
      - bytestring

  loot:
    main: Main.hs
    source-dirs: exe/loot
    dependencies:
      - plunder
      - rainbow
      - bytestring

  server:
    main: Main.hs
    source-dirs: exe/server
    ghc-options: "-O2 -threaded -rtsopts -with-rtsopts=-N"
    dependencies:
      - plunder

tests:
  natty-tests:
    source-dirs: exe/natty-tests
    main: Main.hs
    ghc-options: "-O2 -threaded -rtsopts -with-rtsopts=-N"
    dependencies:
      - base
      - bytestring
      - plunder
      - QuickCheck
      - text
      - vector

  jar-tests:
    source-dirs: exe/jar-tests
    main: Main.hs
    ghc-options: "-O2 -threaded -rtsopts -with-rtsopts=-N"
    dependencies:
      - base
      - bytestring
      - plunder
      - QuickCheck
      - text
      - vector

  rex-tests:
    source-dirs: exe/rex-tests
    main: Main.hs
    dependencies:
      - plunder

  loot-tests:
    source-dirs: exe/loot-tests
    main: Main.hs
    dependencies:
      - plunder

  sire-tests:
    source-dirs: exe/sire-tests
    main: Main.hs
    dependencies:
      - plunder

benchmarks:
  natty-bench:
    source-dirs: exe/natty-bench
    main: Main.hs
    ghc-options: "-O2 -threaded -rtsopts -with-rtsopts=-N"
    dependencies:
      - plunder

dependencies:
- base
- base16-bytestring
- base58-bytestring
- blake3
- bytestring
- classy-prelude
- conduit
- containers
- criterion
- deepseq
- directory
- ed25519
- entropy
- exceptions
- focus
- ghc-prim
- hashable
- hashtables
- heap
- http-types
- integer-gmp
- lmdb
- megaparsec
- memory
- mtl
- optics
- optparse-applicative
- pretty-show
- primitive
- QuickCheck
- rainbow
- random
- random-shuffle
- resourcet
- stm
- stm-chans
- stm-containers
- stm-delay
- tasty
- tasty-golden
- tasty-quickcheck
- terminal-size
- text
- text-builder
- time
- transformers
- unboxed-ref
- unix
- utf8-string
- vector
- wai
- warp

default-extensions:
- ApplicativeDo
- BangPatterns
- BlockArguments
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveDataTypeable
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- EmptyCase
- EmptyDataDecls
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImplicitParams
- LambdaCase
- MagicHash
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- NumericUnderscores
- OverloadedLabels
- OverloadedStrings
- PartialTypeSignatures
- PatternSynonyms
- QuasiQuotes
- Rank2Types
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances
- UnicodeSyntax
- ViewPatterns
